### ISSUE TITLE
Missing on API

### ISSUE THREAD

**Issue by edudouglas** [Ilhasoft/voices-of-youth#11]
User
    Login
    Register
    Auth

Search

Notifications

My Reports
    List (Approved/Pending/Reject)
    Search

Themes
    Filter by year

Theme
    Latest reports

Gallery
    All images
    Filter by report

Comments
    New
    Edit
    Delete

Reports
    New
    Edit

**Comment by eltonplima** [comment]
This issue has been splitted.
