### ISSUE TITLE
[Front-end] Comment date's wrong

### ISSUE THREAD

**Issue by jonasilhasoft** [Ilhasoft/voices-of-youth#30]
When user add comments on Report, the date showed is different the current date.  
<img width="1565" alt="captura de tela 2017-11-28 as 14 55 21" src="https://user-images.githubusercontent.com/34071341/33335576-3b1431f2-d44c-11e7-9e57-d816a6dd1b6c.png">

**Comment by eltonplima** [comment]
Please test and report any problem related.

**Comment by jonasilhasoft** [comment]
Now it's ok, good job!
Thanks!
