### ISSUE TITLE
[Front-end] A logged user isn't correctly identified in comments.

### ISSUE THREAD

**Issue by jonasilhasoft** [Ilhasoft/voices-of-youth#33]
How to reproduce it?

0 - Comment on the report without doing log in.
1 - The comment is sent to the back-end to be approved;
2 - The comment was approved and it's showed after reload the page comments;
3 - On back-end (simulating a response to the previous comment) send a comment logged in as admin user;
4 - The comment is shown in the page comments on the report;
5 - On front-end, logged in, I can see the options to Edit or Remove my comment inserted on the back-end;
6 - I try send another comment by the front-end, logged in;
7 - The comment was sent to the back-end to be  approved;
8 - The comment is shown in the page comments but the username showing "Guest" and the options to Edit or Remove the comment doesn't show.

<img width="706" alt="captura de tela 2017-11-29 as 16 11 46" src="https://user-images.githubusercontent.com/34071341/33395140-516cddbe-d523-11e7-86b7-d25cc2ccdb7f.png">

**Comment by jonasilhasoft** [comment]
When I tried again, after approved on back-end, the username and the options Edit and Remove were shown on front-end. 

<img width="711" alt="captura de tela 2017-11-29 as 16 56 26" src="https://user-images.githubusercontent.com/34071341/33396112-5697b310-d526-11e7-94fe-47ea90604c34.png">

So, I think the bug ocorred in the first comment after do the login, look:
I opened another anonymous tab and I did the process again, the result follows: 

<img width="705" alt="captura de tela 2017-11-29 as 17 01 02" src="https://user-images.githubusercontent.com/34071341/33396519-861956a6-d527-11e7-9be5-b8b772c134a0.png">

<img width="712" alt="captura de tela 2017-11-29 as 17 03 46" src="https://user-images.githubusercontent.com/34071341/33396531-8d3c0686-d527-11e7-8bd8-687e51d5dae4.png">

<img width="621" alt="captura de tela 2017-11-29 as 17 04 10" src="https://user-images.githubusercontent.com/34071341/33396541-9468a220-d527-11e7-84b4-c0b51dbdcfc2.png">

**Comment by eltonplima** [comment]
Please try again.

**Comment by jonasilhasoft** [comment]
Fixed! Good job, guys!
